# Generated by Django 5.0.7 on 2024-07-19 16:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0002_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 19, 16, 2, 29, 693000, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spends', to='sb.subcategory'),
        ),
    ]
