# Generated by Django 5.0.7 on 2024-07-22 14:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0003_alter_spend_date_alter_spend_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='max_allowed_spend',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 14, 37, 55, 444029, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='sb.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='max_allowed_spend',
            field=models.IntegerField(null=True),
        ),
    ]
