# Generated by Django 5.0.7 on 2024-08-06 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0005_alter_category_max_allowed_spend_alter_spend_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
