# Generated by Django 5.0.7 on 2024-08-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb', '0006_alter_spend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='sb.category'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='sb.subcategory'),
        ),
    ]
